import { ScrollView } from "std-widgets.slint";

export struct GridItem {
  image: image,
  index: int,
}

export enum ViewMode {
    full,
    grid,
}

export component MainWindow inherits Window {
    title: "Luminous";
    background: #000000;
    preferred-width: 1280px;
    preferred-height: 720px;
    full-screen: self.is_fullscreen;

    // Full view
    callback request_next_image();
    callback request_prev_image();

    // Grid view
    callback request_grid_data(int, int);
    callback image_selected(int);

    // ContextMenuArea
    callback rotate_plus_90();
    callback rotate_minus_90();

    callback quit_app();

    in property <[GridItem]> grid_model;
    in property <image> full_view_image;
    in-out property <int> curr_image_index: 0;
    in property <string> curr_image_name;
    in-out property <ViewMode> view_mode: ViewMode.full; // grid;
    in-out property <bool> is_fullscreen: false;
    in-out property <int> grid_cols: 5;

    // TODO: pass to Rust
    // in-out property <length> curr_mouse_x: 0px;
    // in-out property <length> curr_mouse_y: 0px;

    function udpate_visible_rows() {
        let item_h = grid_container.item-size + grid_container.gap;
        let cols = grid_container.cols;

        if (item_h > 1px && root.height > 1px) {
            let start_row = floor(-grid_view.viewport-y / item_h);
            let screen_rows = ceil(grid_view.height / item_h);
            let buffer_rows = 5;
            let start_index = Math.max(0, (start_row - buffer_rows) * cols);
            let total_count = (screen_rows + (buffer_rows * 2)) * cols;
            debug("start_index: ", start_index, " total_count: ", total_count);
            root.request_grid_data(start_index, total_count);
        }
    }

    forward-focus: my-key-handler;
    my-key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == "q") {
                root.quit_app();
                return accept;
            }
            if (event.text == "f") {
                root.is_fullscreen = !root.is_fullscreen;
                return accept;
            }
            if (root.view-mode == ViewMode.full) {
                if (event.text == "h" || event.text == Key.LeftArrow) {
                    root.request_prev_image();
                } else if (event.text == "l" || event.text == Key.RightArrow) {
                    root.request_next_image();
                } else if (event.text == Key.Escape) {
                    root.view_mode = ViewMode.grid;
                }
            } else if (root.view-mode == ViewMode.grid) {
                if (event.text == Key.Escape) {
                    root.view_mode = ViewMode.full;
                }
                if (event.text == Key.PageDown) {
                    grid_view.viewport-y = Math.max(
                        grid_view.viewport-y - grid_view.height,
                        grid_view.height - grid_view.viewport-height);
                    udpate_visible_rows();
                    return accept;
                }
                if (event.text == Key.PageUp) {
                    grid_view.viewport-y = Math.min(
                        grid_view.viewport-y + grid_view.height,
                        0px);
                    udpate_visible_rows();
                    return accept;
                }
            }
            accept
        }
    }

    grid_view := ScrollView {
        visible: root.view-mode == ViewMode.grid;
        viewport-height: grid_container.height;

        scrolled => {
            udpate_visible_rows();
        }
        // FIX: Rust does not react init. Does it depend on grid_container?
        init => {
            udpate_visible_rows();
        }
        // Could be refreshed too much while resizing...
        changed height => {
            debug("new height: ", self.height);
            udpate_visible_rows();
        }
        changed width => {
            debug("new width: ", self.width);
            udpate_visible_rows();
        }
        TouchArea {
            width: 100%;
            property <int> step: 0;
            property <int> cols: root.grid_cols;
            property <length> gap: 0px;
            property <length> item-size: (parent.width - (cols + 1) * gap) / cols;
            property <int> rows: (root.grid_model.length + cols - 1) / cols;
            height: (rows * item-size) + ((rows + 1) * gap);

            scroll-event(event) => {
                if (event.modifiers.control) {
                    if event.delta-y > 0 {
                        step = -1;
                    } else if event.delta-y < 0 {
                        step = 1;
                    }
                    root.grid_cols = clamp(root.grid_cols + step, 1, 20);
                    accept
                }
                reject
            }

            grid_container := Rectangle {
                width: parent.width;
                height: parent.height;
                property <length> item-size: parent.item-size;
                property <length> gap: parent.gap;
                property <int> cols: parent.cols;

                for item[i] in root.grid_model: Rectangle {
                    width: parent.item-size;
                    height: parent.item-size;
                    x: (Math.mod(i, parent.cols) * (parent.item-size + parent.gap)) + parent.gap;
                    y: (floor(i / parent.cols) * (parent.item-size + parent.gap)) + parent.gap;

                    clip: true;
                    Image {
                        source: item.image;
                        image-fit: cover;
                        width: 100%;
                        height: 100%;
                    }

                    TouchArea {
                        clicked => {
                            root.image_selected(item.index);
                            root.view_mode = ViewMode.full;
                        }
                    }
                }
            }
        }
    }

    full_view := TouchArea {
        visible: root.view-mode == ViewMode.full;
        width: 100%;
        height: 100%;

        scroll-event(event) => {
            if (event.delta-y > 0) {
                root.request_prev_image();
            } else if (event.delta-y < 0) {
                root.request_next_image();
            }
            accept
        }

        rect_img := TouchArea {
            Image {
                source: root.full_view_image;
                image-fit: contain;
                width: 100%;
                height: 100%;
                Rectangle {
                    height: 16px;
                    y: parent.height - self.height;
                    width: 100%;
                    background: #000000a0;
                    HorizontalLayout {
                        Text {
                            color: white;
                            font-size: 12px;
                            text: (curr_image_index + 1) + "/" + grid_model.length;
                        }

                        Text {
                            color: white;
                            font-size: 12px;
                            text: curr_image_name;
                        }

                        // Text {
                        //     // FIX: Needs rate limitting
                        //     text: "[x,y]=[" + rect_img.mouse-x / 1px + "," + rect_img.mouse-y / 1px + "]";
                        // }
                    }
                }
            }

            ContextMenuArea {
                Menu {
                    MenuItem {
                        title: @tr("Rotate +90");
                        activated => {
                            debug("Rotate +90");
                            rotate_plus_90();
                        }
                    }

                    MenuItem {
                        title: @tr("Rotate -90");
                        activated => {
                            debug("Rotate -90");
                            rotate_minus_90();
                        }
                    }
                }
            }
        }
    }
}
