import { Button, Palette } from "std-widgets.slint";
export enum ViewMode {
    full,
    grid,
}

export enum ImgFmt {
    png,
    jpeg,
    webp,
}

export enum EditOpKind {
    RotateCW,
    RotateCCW,
    FlipH,
    FlipV,
    Brighten,
    Contrast,
    Crop,
    ColorSpace,
    Reset,
    Copy,
    Delete,
    Save,
}

export enum Channel {
    Gray,
    Red,
    Green,
    Blue,
    Hue,
    Saturation,
    Value,
}

export struct EditOp {
    kind: EditOpKind,
    int-val: int,
    float-val: float,
    string-val: string,
}

export struct GridItem {
    image: image,
    index: int,
    abs_index: int,
    selected: bool,
}

export component NoImage inherits Rectangle {
    background: Palette.background;
    height: 100px;
    width: 250px;
    border-radius: 5px;

    callback open-clicked();

    VerticalLayout {
        spacing: 10px;

        Text {
            font-size: 16px;
            text: "No Images";
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        open-folder-btn := Button {
            text: "Open folder";
            clicked => {
                open-clicked();
            }
        }
    }
}
