export enum ViewMode {
    full,
    grid,
}

export enum ImgFmt {
    png,
    jpeg,
    webp,
}

export enum EditOpKind {
    RotateCW,
    RotateCCW,
    FlipH,
    FlipV,
    Brighten,
    Contrast,
    Crop,
    Reset,
}

export struct EditOp {
    kind: EditOpKind,
    int-val: int,
    float-val: float,
}

export struct GridItem {
    image: image,
    index: int,
    abs_index: int,
    selected: bool,
}
