import { SpinBox, Button, ComboBox } from "std-widgets.slint";
import { Channel, EditOp, EditOpKind } from "common.slint";

component EditRow inherits HorizontalLayout {
    in property <string> label;
    spacing: 8px;
    padding-top: 4px;
    padding-bottom: 4px;
    height: 32px;

    Text {
        text: root.label;
        vertical-alignment: center;
        width: 64px;
    }

    @children
}

export component EditsPanel inherits Rectangle {
    callback apply-edit(EditOp);

    out property <int> brightness <=> brightness-spin.value;
    out property <int> contrast <=> contrast-spin.value;

    VerticalLayout {
        padding: 10px;
        spacing: 2px;

        EditRow {
            label: "Rotate";
            Button {
                text: "−90°";
                clicked => {
                    root.apply-edit({ kind: EditOpKind.RotateCCW });
                }
            }

            Button {
                text: "+90°";
                clicked => {
                    root.apply-edit({ kind: EditOpKind.RotateCW });
                }
            }
        }

        EditRow {
            label: "Flip";
            Button {
                text: "H";
                clicked => {
                    root.apply-edit({ kind: EditOpKind.FlipH });
                }
            }

            Button {
                text: "V";
                clicked => {
                    root.apply-edit({ kind: EditOpKind.FlipV });
                }
            }
        }

        EditRow {
            label: "Brightness";
            brightness-spin := SpinBox {
                value: 0;
                minimum: -255;
                maximum: 255;
                edited(v) => {
                    root.apply-edit({ kind: EditOpKind.Brighten, int-val: v });
                }
            }
        }

        EditRow {
            label: "Contrast";
            contrast-spin := SpinBox {
                value: 0;
                minimum: -100;
                maximum: 100;
                edited(v) => {
                    root.apply-edit({ kind: EditOpKind.Contrast, int-val: v, float-val: v / 100.0 });
                }
            }
        }

        EditRow {
            label: "Color Space";
            channel-combo-box := ComboBox {
                model: ["RGB", "HSV", "Gray", "Red", "Green", "Blue", "Hue", "Saturation", "Value"];
                selected(color-space) => {
                    debug("Selected ColorSpace: ", color-space);
                    root.apply-edit({ kind: EditOpKind.ColorSpace, string-val: color-space });
                }
            }
        }

        EditRow {
            Button {
                text: "Reset";
                clicked => {
                    root.apply-edit({ kind: EditOpKind.Reset });
                }
            }
        }
    }
}
