import { Palette, TabWidget, Button, StandardButton } from "std-widgets.slint";
import { ImgFmt, EditOp, EditOpKind } from "common.slint";
import { SidePanel } from "side-panel.slint";
import { EditsPanel } from "edits-panel.slint";
import { SelectRect, ImgRect } from "select-rect.slint";
import { InteractivePlugin, Plugin } from "plugins.slint";
import { ExifTable } from "exif.slint";

export global FullViewState {
    in property <image> curr-image;
    in property <string> curr-image-name;
    in property <int> curr-image-index;
    in property <[[StandardListViewItem]]> exif-rows;

    callback request-next-image();
    callback request-prev-image();

    in property <[Plugin]> interactive-plugins;
    in property <image> mask-overlay;
    callback clear-curr-mask-overlay();
    callback save-curr-mask-overlay();
    callback request-segmentation(string, int, int, int, int, string);

    in property <[string]> encoder_extensions;
    callback save-with-format(string);
    in property <ImgRect> selection;
    callback apply-edit(EditOp);
}

export component DeleteConfirmPopup inherits PopupWindow {
    width: 225px;
    height: 100px;
    callback confirmed();
    callback canceled();

    Rectangle {
        background: Palette.background;
        border-color: Palette.border;
        border-radius: 5px;
        border-width: 1px;

        VerticalLayout {
            Text {
                text: "Move image to trash?";
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            HorizontalLayout {
                StandardButton {
                    kind: cancel;
                    clicked => {
                        canceled();
                    }
                }

                StandardButton {
                    kind: ok;
                    clicked => {
                        confirmed();
                    }
                }
            }
        }
    }
}

export component FullView inherits TouchArea {
    in property <int> total-images;
    in property <bool> timer-running: false;
    in-out property <bool> panel-visible: false;

    callback exit-full-view();

    // TODO: Not my proudest moments, but it works... revisit
    property <int> interactive-plugins-idx: -1;

    property <string> display-coords: "0,0";
    property <int> zoom-scale-percentage: 100;
    property <float> zoom-scale: 1.0;
    property <length> last-coords-x;
    property <length> last-coords-y;
    property <length> start-drag-x;
    property <length> start-drag-y;
    property <float> start-pan-x: 0.5;
    property <float> start-pan-y: 0.5;
    property <length> side-panel-width: 240px;
    property <bool> dragging: false;
    property <float> pinch-initial-scale: 1.0;

    property <float> pan-pos-x: 0.5;
    property <float> pan-pos-y: 0.5;

    property <float> img-render-scale: (FullViewState.curr-image.width > 0 && FullViewState.curr-image.height > 0) ? Math.min(img-el.width / FullViewState.curr-image.width, img-el.height / FullViewState.curr-image.height) / 1px : 1.0;

    property <length> img-vis-x: img-el.x + (img-el.width - FullViewState.curr-image.width * 1px * img-render-scale) / 2;
    property <length> img-vis-y: img-el.y + (img-el.height - FullViewState.curr-image.height * 1px * img-render-scale) / 2;

    property <bool> rmb-down;
    property <bool> show-context-menu;

    mouse-cursor: (root.dragging && zoom-scale > 1.0) ? grabbing : crosshair;

    coords-timer := Timer {
        interval: 60ms;
        running: root.timer-running;
        triggered => {
            if (root.mouse-x != root.last-coords-x || root.mouse-y != root.last-coords-y) {
                root.last-coords-x = root.mouse-x;
                root.last-coords-y = root.mouse-y;
                if (FullViewState.curr-image.width > 0 && FullViewState.curr-image.height > 0) {
                    let rel-x = root.mouse-x - img-rect.x;
                    let rel-y = root.mouse-y - img-rect.y;
                    let x = clamp(Math.round((rel-x - root.img-vis-x) / (root.img-render-scale * 1px)), 0, FullViewState.curr-image.width);
                    let y = clamp(Math.round((rel-y - root.img-vis-y) / (root.img-render-scale * 1px)), 0, FullViewState.curr-image.height);
                    root.display-coords = x + "," + y;
                }
            }
            zoom-scale-percentage = round(zoom-scale * 100);
        }
    }

    public function reset-zoom() {
        zoom-scale = 1;
        pan-pos-x = 0.5;
        pan-pos-y = 0.5;
    }

    function zoom(scale-delta: float, center-x: length, center-y: length) {
        let old-scale = zoom-scale;
        let new-scale = clamp(zoom-scale * scale-delta, 1, 10.0);
        if (old-scale == new-scale) {
            return;
        }
        let rel-x = center-x - img-rect.x;
        let rel-y = center-y - img-rect.y;
        let old-img-w = img-rect.width * old-scale;
        let old-img-h = img-rect.height * old-scale;
        let old-x = (img-rect.width - old-img-w) * pan-pos-x;
        let old-y = (img-rect.height - old-img-h) * pan-pos-y;

        let ratio = new-scale / old-scale;
        let new-img-w = img-rect.width * new-scale;
        let new-img-h = img-rect.height * new-scale;

        let new-x = rel-x - (rel-x - old-x) * ratio;
        let new-y = rel-y - (rel-y - old-y) * ratio;

        zoom-scale = new-scale;
        if (new-img-w > img-rect.width) {
            pan-pos-x = clamp(new-x / (img-rect.width - new-img-w), 0, 1);
        }
        if (new-img-h > img-rect.height) {
            pan-pos-y = clamp(new-y / (img-rect.height - new-img-h), 0, 1);
        }
    }

    function zoom-to-selection() {
        if (select-rect.selection.w < 1px || select-rect.selection.h < 1px) {
            return;
        }
        let cx = root.img-vis-x + (select-rect.selection.x + select-rect.selection.w / 2) * root.img-render-scale + img-rect.x;
        let cy = root.img-vis-y + (select-rect.selection.y + select-rect.selection.h / 2) * root.img-render-scale + img-rect.y;
        let zoom-factor = Math.min(img-rect.width / (select-rect.selection.w * root.img-render-scale), img-rect.height / (select-rect.selection.h * root.img-render-scale));
        zoom(zoom-factor, cx, cy);
    }

    function to-image-coords(screen-x: length, screen-y: length) -> { x: int, y: int} {
        let rel-x = screen-x - img-rect.x;
        let rel-y = screen-y - img-rect.y;
        return {
            x: clamp(Math.round((rel-x - root.img-vis-x) / (root.img-render-scale * 1px)), 0, FullViewState.curr-image.width),
            y: clamp(Math.round((rel-y - root.img-vis-y) / (root.img-render-scale * 1px)), 0, FullViewState.curr-image.height),
        };
    }

    pointer-event(event) => {
        context-menu.enabled = false;
        if (event.button == PointerEventButton.middle) {
            if (event.kind == PointerEventKind.down) {
                root.start-drag-x = root.mouse-x;
                root.start-drag-y = root.mouse-y;
                root.start-pan-x = root.pan-pos-x;
                root.start-pan-y = root.pan-pos-y;
                root.dragging = true;
            } else if (event.kind == PointerEventKind.up) {
                root.dragging = false;
            }
        }
        if (event.button == PointerEventButton.left) {
            if (event.kind == PointerEventKind.down) {
                root.start-drag-x = root.mouse-x;
                root.start-drag-y = root.mouse-y;
                select-rect.show(root.mouse-x - img-rect.x, root.mouse-y - img-rect.y);
            } else if (event.kind == PointerEventKind.up) {
                if (select-rect.selection.w < 2px || select-rect.selection.h < 2px) {
                    if FullViewState.curr-image.width > 0 {
                        let coords = root.to-image-coords(root.mouse-x, root.mouse-y);
                        if interactive-plugins-idx > -1 && FullViewState.interactive-plugins[interactive-plugins-idx].click-active {
                            debug("request-segmentation:", FullViewState.interactive-plugins[interactive-plugins-idx].id, interactive-plugins-idx);
                            FullViewState.request-segmentation(FullViewState.interactive-plugins[interactive-plugins-idx].id, coords.x, coords.y, -1, -1, "");
                        } else if interactive-plugins-idx > -1 && FullViewState.interactive-plugins[interactive-plugins-idx].select-active && coords.x != coords.x + select-rect.selection.w / 1px {
                            select-rect.confirmed();
                        }
                    }
                    select-rect.hide();
                }
            }
        }
        if (event.button == PointerEventButton.right) {
            if (event.kind == PointerEventKind.down) {
                root.start-drag-x = root.mouse-x;
                root.start-drag-y = root.mouse-y;
                root.start-pan-x = root.pan-pos-x;
                root.start-pan-y = root.pan-pos-y;
                root.dragging = true;
                rmb-down = true;
                show-context-menu = true;
            } else if (event.kind == PointerEventKind.up) {
                root.dragging = false;
                rmb-down = false;
                if (show-context-menu) {
                    context-menu.enabled = true;
                    context-menu.show({ x: root.mouse-x, y: root.mouse-y });
                }
            }
        }
    }

    moved => {
        if (dragging && zoom-scale > 1.0) {
            show-context-menu = false;
            let dx = root.mouse-x - root.start-drag-x;
            let dy = root.mouse-y - root.start-drag-y;
            let overflow-x = img-rect.width * (zoom-scale - 1);
            let overflow-y = img-rect.height * (zoom-scale - 1);
            if (overflow-x > 0px) {
                root.pan-pos-x = clamp(root.start-pan-x - dx / overflow-x, 0, 1);
            }
            if (overflow-y > 0px) {
                root.pan-pos-y = clamp(root.start-pan-y - dy / overflow-y, 0, 1);
            }
        }
        if (root.pressed && !dragging) {
            select-rect.update-selection(
                { x: root.start-drag-x - img-rect.x, y: root.start-drag-y - img-rect.y },
                { x: root.mouse-x - img-rect.x, y: root.mouse-y - img-rect.y },
            );
        }
    }

    scroll-event(event) => {
        let scroll-up = event.delta-y > 0;
        if (event.modifiers.control || rmb-down) {
            zoom(scroll-up ? 1.1 : 0.9, root.mouse-x, root.mouse-y);
            show-context-menu = false;

            root.start-pan-x = root.pan-pos-x;
            root.start-pan-y = root.pan-pos-y;
            root.start-drag-x = root.mouse-x;
            root.start-drag-y = root.mouse-y;
        } else {
            if (zoom-scale > 1) {
                return reject;
            }
            select-rect.cancelled();
            if (scroll-up) {
                FullViewState.request-prev-image();
            } else {
                FullViewState.request-next-image();
            }
        }
        accept
    }

    HorizontalLayout {
        img-rect := Rectangle {
            horizontal-stretch: 1;
            clip: true;

            img-el := Image {
                source: FullViewState.curr-image;
                image-fit: contain;
                width: parent.width * root.zoom-scale;
                height: parent.height * root.zoom-scale;
                x: (parent.width - self.width) * root.pan-pos-x;
                y: (parent.height - self.height) * root.pan-pos-y;
            }

            Image {
                source: FullViewState.mask-overlay;
                image-fit: contain;
                width: img-el.width;
                height: img-el.height;
                x: img-el.x;
                y: img-el.y;
            }

            footer := Rectangle {
                visible: true;
                height: 18px;
                y: parent.height - self.height;
                width: parent.width;
                background: Palette.background.with-alpha(50%);

                Text {
                    x: 5px;
                    text: (FullViewState.curr-image-index + 1) + "/" + total-images + " - " + zoom-scale-percentage + "%";
                }

                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: FullViewState.curr-image-name;
                    overflow: elide;
                }

                Text {
                    x: parent.width - self.width - 5px;
                    text: "[x,y]=[" + display-coords + "]";
                }
            }

            select-rect := SelectRect {
                img-offset-x: root.img-vis-x;
                img-offset-y: root.img-vis-y;
                img-scale: root.img-render-scale;
                confirmed => {
                    debug("select-rect confirmed");
                    if (select-rect.selection.w > 2px && select-rect.selection.h > 2px) {
                        if interactive-plugins-idx > -1 && FullViewState.interactive-plugins[interactive-plugins-idx].select-active {
                            let r = select-rect.selection;
                            debug("request-segmentation:", FullViewState.interactive-plugins[interactive-plugins-idx].id, interactive-plugins-idx);
                            FullViewState.request-segmentation(FullViewState.interactive-plugins[interactive-plugins-idx].id, r.x / 1px, r.y / 1px, (r.x + r.w) / 1px, (r.y + r.h) / 1px, "");
                        } else {
                            root.zoom-to-selection();
                        }
                    }
                    select-rect.hide();
                }
                cancelled => {
                    // debug("select-rect cancelled");
                    select-rect.hide();
                }
            }

            context-menu := ContextMenuArea {
                Menu {
                    MenuItem {
                        title: @tr("Rotate +90");
                        activated => {
                            FullViewState.apply-edit({ kind: EditOpKind.RotateCW });
                        }
                    }

                    MenuItem {
                        title: @tr("Rotate -90");
                        activated => {
                            FullViewState.apply-edit({ kind: EditOpKind.RotateCCW });
                        }
                    }

                    MenuItem {
                        title: @tr("Crop");
                        activated => {
                            let r = select-rect.selection;
                            if (r.w > 2px && r.h > 2px && select-rect.visible) {
                                debug("Crop (x,y,w,h):", r.x, r.y, r.w, r.h);
                                FullViewState.selection = { x: r.x, y: r.y, w: r.w, h: r.h };
                                FullViewState.apply-edit({ kind: EditOpKind.Crop });
                                select-rect.hide();
                                reset-zoom();
                            } else {
                                debug("Crop ignored, selection is none");
                            }
                        }
                    }

                    MenuItem {
                        title: @tr("Flip Horizontal");
                        activated => {
                            FullViewState.apply-edit({ kind: EditOpKind.FlipH });
                        }
                    }

                    MenuItem {
                        title: @tr("Flip Vertical");
                        activated => {
                            FullViewState.apply-edit({ kind: EditOpKind.FlipV });
                        }
                    }

                    MenuItem {
                        title: @tr("Reset image edits");
                        activated => {
                            FullViewState.apply-edit({ kind: EditOpKind.Reset });
                        }
                    }

                    MenuItem {
                        title: @tr("Copy to clipboard");
                        activated => {
                            FullViewState.apply-edit({ kind: EditOpKind.Copy });
                        }
                    }

                    MenuItem {
                        title: @tr("Delete");
                        activated => {
                            show-delete-popup();
                        }
                    }

                    MenuSeparator { }

                    MenuItem {
                        title: @tr("Reset zoom");
                        activated => {
                            root.reset-zoom();
                        }
                    }

                    MenuItem {
                        title: @tr("Toggle footer");
                        activated => {
                            footer.visible = !footer.visible;
                        }
                    }

                    // TODO
                    // MenuItem {@tr("Save (overwrite)");}
                    Menu {
                        title: @tr("Save with format");
                        for ext in FullViewState.encoder_extensions: MenuItem {
                            title: ext;
                            activated => {
                                FullViewState.save-with-format(ext);
                            }
                        }
                    }
                }
            }
        }

        SidePanel {
            is-visible: root.panel-visible;
            side-width <=> root.side-panel-width;

            TabWidget {
                current-index: 0;
                Tab {
                    title: "Edit";
                    EditsPanel {
                        apply-edit(op) => {
                            FullViewState.apply-edit(op);
                        }
                    }
                }

                Tab {
                    title: "Metadata";
                    VerticalLayout {
                        Text {
                            horizontal-alignment: center;
                            text: "WxH = " + FullViewState.curr-image.width + "x" + FullViewState.curr-image.height;
                        }

                        ExifTable {
                            exif-rows: FullViewState.exif-rows;
                        }
                    }
                }

                Tab {
                    title: "Plugins";
                    VerticalLayout {
                        padding-top: 2px;
                        spacing: 5px;
                        HorizontalLayout {
                            Button {
                                text: "Clear mask";
                                clicked => {
                                    FullViewState.clear-curr-mask-overlay();
                                }
                            }

                            Button {
                                text: "Save mask";
                                clicked => {
                                    FullViewState.save-curr-mask-overlay();
                                }
                            }
                        }

                        // TODO: How do I make mutally exclusive checked buttons?
                        for plugin[i] in FullViewState.interactive-plugins: InteractivePlugin {
                            plugin: FullViewState.interactive-plugins[i];

                            interactive-text-submitted(txt) => {
                                FullViewState.request-segmentation(plugin.id, 0, 0, 0, 0, txt);
                            }
                            click-active-changed(active) => {
                                debug("click-active-changed", interactive-plugins-idx, i);
                                FullViewState.interactive-plugins[i].click-active = active;
                                if interactive-plugins-idx > -1 && interactive-plugins-idx != i {
                                    // plugin.click-active = false;
                                    // plugin.select-active = false;
                                    FullViewState.interactive-plugins[i].click-active = false;
                                    FullViewState.interactive-plugins[i].select-active = false;
                                }
                                interactive-plugins-idx = i;
                            }
                            select-active-changed(active) => {
                                debug("select-active-changed", interactive-plugins-idx, i);
                                FullViewState.interactive-plugins[i].select-active = active;
                                if interactive-plugins-idx > -1 && interactive-plugins-idx != i {
                                    // plugin.click-active = false;
                                    // plugin.select-active = false;
                                    FullViewState.interactive-plugins[i].click-active = false;
                                    FullViewState.interactive-plugins[i].select-active = false;
                                }
                                interactive-plugins-idx = i;
                            }
                        }

                        Rectangle { }
                    }
                }
            }
        }
    }

    delete-popup := DeleteConfirmPopup {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        confirmed => {
            FullViewState.apply-edit({ kind: EditOpKind.Delete });
        }
    }

    public function show-delete-popup() {
        delete-popup.show();
    }
}
