import { GridView, GridViewState } from "grid-view.slint";
import { FullView, FullViewState } from "full-view.slint";
import { Palette } from "std-widgets.slint";
import { ImgFmt, EditOp, EditOpKind, GridItem, ViewMode } from "common.slint";
import { PipelineStep, PipelineStepKind, RotateAngle } from "side-panel.slint";

export { GridItem, ViewMode } from "common.slint";
export { FullViewState } from "full-view.slint";
export { GridViewState } from "grid-view.slint";
export { SettingsState } from "settings.slint";


export component MainWindow inherits Window {
    title: {
        if view-mode == ViewMode.grid {
            "Luminous"
        } else {
            (FullViewState.curr-image-index + 1) + "/" + full-ui.total-images + " - " + FullViewState.curr-image-name
        }
    };
    background: app-background;
    preferred-width: 1280px;
    preferred-height: 720px;
    full-screen: false;

    // App Callbacks
    callback quit-app();
    callback open-images();

    // App State
    in property <color> app-background: Palette.background;
    in-out property <ViewMode> view-mode: ViewMode.grid;
    in property <[string]> encoder_extensions;

    // Bindings
    in property <string> bind-quit;
    in property <string> bind-fullscreen;
    in property <string> bind-show-settings;
    in property <string> bind-switch-view-mode;
    in property <string> bind-reset-zoom;
    in property <string> bind-grid-pg-dn;
    in property <string> bind-grid-pg-up;
    in property <string> bind-toggle-side-panel;
    in property <string> bind-copy-to-clipboard;
    in property <string> bind-delete;

    public function return-focus() {
        key-handler.focus();
    }

    forward-focus: key-handler;
    key-handler := FocusScope {
        KeyBinding {
            keys: @keys(Home);
            activated => {
                if (root.view-mode == ViewMode.grid) {
                    grid-ui.page-top();
                }
            }
        }

        KeyBinding {
            keys: @keys(End);
            activated => {
                if (root.view-mode == ViewMode.grid) {
                    grid-ui.page-bottom();
                }
            }
        }

        key-pressed(event) => {
            if (event.text == root.bind-quit) {
                root.quit-app();
                return accept;
            }
            if (event.text == root.bind-fullscreen) {
                root.full-screen = !root.full-screen;
                return accept;
            }
            if (event.text == root.bind-switch-view-mode) {
                root.view-mode = root.view-mode == ViewMode.full ? ViewMode.grid : ViewMode.full;
                full-ui.reset-zoom();
                return accept;
            }
            if (root.view-mode == ViewMode.full) {
                if (event.text == "h" || event.text == Key.LeftArrow) {
                    full-ui.reset-zoom();
                    FullViewState.request-prev-image();
                    return accept;
                }
                if (event.text == "l" || event.text == Key.RightArrow) {
                    full-ui.reset-zoom();
                    FullViewState.request-next-image();
                    return accept;
                }
                if (event.text == root.bind-reset-zoom) {
                    full-ui.reset-zoom();
                    return accept;
                }
                if (event.text == root.bind-toggle-side-panel) {
                    FullViewState.side-panel-visible = !FullViewState.side-panel-visible;
                    return accept;
                }
                if (event.text == root.bind-copy-to-clipboard) {
                    FullViewState.apply-edit({ kind: EditOpKind.Copy });
                }
                if (event.text == root.bind-delete) {
                    full-ui.show-delete-popup();
                }
            } else if (root.view-mode == ViewMode.grid) {
                if (event.text == root.bind-show-settings) {
                    grid-ui.show-settings();
                }
                if (event.text == root.bind-grid-pg-dn) {
                    grid-ui.page-down();
                    return accept;
                }
                if (event.text == root.bind-grid-pg-up) {
                    grid-ui.page-up();
                    return accept;
                }
                if (event.text == "=" || event.text == "+") {
                    grid-ui.update-grid-cols(GridViewState.grid-cols - 1);
                    return accept;
                }
                if (event.text == "-" || event.text == "_") {
                    grid-ui.update-grid-cols(GridViewState.grid-cols + 1);
                    return accept;
                }
                if (event.text == "/") {
                    grid-ui.focus-search();
                    return accept;
                }
                if (event.text == root.bind-toggle-side-panel) {
                    GridViewState.side-panel-visible = !GridViewState.side-panel-visible;
                    return accept;
                }
            }
            reject
        }
    }

    // ----- Grid view -----
    callback batch-save-with-format(ImgFmt);

    // Pipeline
    in-out property <[PipelineStep]> pipeline-steps;
    in property <float> pipeline-progress;
    callback pipeline-add-step(PipelineStepKind);
    callback pipeline-remove-step(int);
    callback pipeline-update-step(int, PipelineStep);
    callback pipeline-run(string);

    grid-ui := GridView {
        visible: root.view-mode == ViewMode.grid;
        forward-focus: key-handler;
        pipeline-steps <=> root.pipeline-steps;
        pipeline-progress <=> root.pipeline-progress;
        encoder_extensions: encoder_extensions;

        batch-save-with-format(fmt) => {
            root.batch-save-with-format(fmt);
        }
        pipeline-add-step(k) => {
            root.pipeline-add-step(k);
        }
        pipeline-update-step(i, s) => {
            root.pipeline-update-step(i, s);
        }
        pipeline-remove-step(i) => {
            root.pipeline-remove-step(i);
        }
        pipeline-run(extension) => {
            root.pipeline-run(extension);
        }
        open-images => {
            open-images();
        }
    }

    // ----- Full view -----
    full-ui := FullView {
        visible: root.view-mode == ViewMode.full;
        timer-running: root.view-mode == ViewMode.full;
        total-images: GridViewState.model.length;
        encoder_extensions: encoder_extensions;

        exit-full-view => {
            root.view-mode = ViewMode.grid;
        }
        open-images => {
            open-images();
        }
    }
}
