import { Palette, Button, LineEdit } from "std-widgets.slint";

export struct Plugin {
    id: string,
    enabled: bool,
    auto-start: bool,
    is-busy: bool,
    state: string, // Starting, Stopping, Enable, Disable
    run-state: string, // NotRunning, Init, Busy, Ready, Error, ...
    click-active: bool,
    select-active: bool,
    click-capability-support: bool,
    select-capability-support: bool,
    text-capability-support: bool,
}

export component InteractivePlugin inherits Rectangle {
    in-out property <Plugin> plugin;

    height: 120px;
    background: Palette.background.brighter(10%);
    border-width: 1px;
    border-color: Palette.border;
    border-radius: 3px;

    callback interactive-text-submitted(string);
    callback click-active-changed(bool);
    callback select-active-changed(bool);
    callback update-run-state();
    callback run(bool);

    VerticalLayout {
        padding: 2px;
        spacing: 2px;
        HorizontalLayout {
            Text {
                text: " " + plugin.id;
                font-size: 14px;
            }

            Text {
                text: plugin.run-state;
                font-size: 14px;
                horizontal-alignment: right;
            }
        }

        Rectangle {
            height: 1px;
            width: 90%;
            background: Palette.border;
        }

        if (plugin.click-capability-support): click-btn := Button {
            text: "Click";
            checked: plugin.click-active;
            clicked => {
                plugin.click-active = !plugin.click-active;
                click-active-changed(plugin.click-active);
                if (plugin.click-active) {
                    plugin.select-active = false;
                }
                debug("click-active", plugin.click-active, "select-active", plugin.select-active);
            }
        }

        if (plugin.select-capability-support): select-btn := Button {
            text: "Select";
            checked: plugin.select-active;
            clicked => {
                plugin.select-active = !plugin.select-active;
                select-active-changed(plugin.select-active);
                if (plugin.select-active) {
                    plugin.click-active = false;
                }
                debug("click-active", plugin.click-active, "select-active", plugin.select-active);
            }
        }

        if (plugin.text-capability-support): text-line-edit := LineEdit {
            placeholder-text: "Enter text here";
            accepted(text) => {
                debug("Accepted: ", text);
                interactive-text-submitted(text);
                self.clear-focus()
            }

            key-pressed(event) => {
                if (event.text == Key.Escape) {
                    self.text = "";
                    interactive-text-submitted("");
                    self.clear-focus();
                    return accept;
                }
                reject
            }
        }
    }
}
