import {
    Palette,
    Button,
    StandardButton,
    VerticalBox,
    ListView,
    StandardListView,
    LineEdit,
} from "std-widgets.slint";
import { Plugin } from "plugins.slint";

export struct SettingItem {
    id: string,
    label: string,
    value: string,
}

export global SettingsState {
    in property <int> image-cache-count;
    callback clear-image-cache();
    callback get-image-cache-count();
    callback settings-opened();

    in property <[Plugin]> plugins;
    in property <[StandardListViewItem]> plugin-names;
    callback toggle-plugin-enable(string);
    callback toggle-plugin-auto-start(string, int);

    in property <[SettingItem]> binding-settings;
    callback update-setting(string, string, string);
}

export component ClearImageCacheDialog inherits Dialog {
    title: "Clear Cache";
    Text {
        text: "Do you want to clear the image cache?";
    }

    StandardButton {
        kind: yes;
    }

    StandardButton {
        kind: no;
    }
}

export component Separator inherits Rectangle {
    height: 1px;
    width: 90%;
    background: Palette.border;
}

export component SettingsSection inherits VerticalLayout {
    in property <string> title;
    spacing: 8px;

    if (title != ""): Text {
        text: title;
        font-size: 14px;
        font-weight: 700;
    }

    Rectangle {
        background: Palette.alternate-background;
        border-radius: 4px;
        VerticalLayout {
            padding: 8px;
            @children
        }
    }
}

export component Settings inherits PopupWindow {
    close-policy: close-on-click-outside;

    Rectangle {
        background: Palette.background;
        border-radius: 3px;
        VerticalLayout {
            Rectangle {
                width: 100%;
                height: 25px;
                background: Palette.alternate-background;
                HorizontalLayout {
                    padding-left: 5px;
                    Text {
                        text: "Settings";
                        font-size: 14px;
                        vertical-alignment: center;
                    }

                    Button {
                        width: parent.height * 2;
                        icon: @image-url("icons/close-button.svg");
                        colorize-icon: true;
                        clicked => {
                            root.close();
                        }
                    }
                }
            }

            VerticalLayout {
                padding: 15px;
                spacing: 10px;

                SettingsSection {
                    HorizontalLayout {
                        alignment: space-between;
                        Text {
                            text: "Image cache: " + SettingsState.image-cache-count;
                            vertical-alignment: center;
                        }

                        Button {
                            text: "Clear";
                            width: 80px;
                            clicked => {
                                SettingsState.clear-image-cache();
                            }
                        }
                    }
                }

                SettingsSection {
                    title: "Plugins";
                    HorizontalLayout {
                        spacing: 10px;
                        Rectangle {
                            height: 150px;
                            background: Palette.background;
                            plugins-list := StandardListView {
                                model: SettingsState.plugin-names;
                                current-item-changed(index) => {
                                    toggle-plugin-enable-btn.checked = SettingsState.plugins[index].state == "Disable";
                                    toggle-plugin-auto-start-btn.checked = SettingsState.plugins[index].auto-start;
                                }
                            }
                        }

                        Rectangle {
                            width: 200px;
                            VerticalLayout {
                                property <int> idx: plugins-list.current-item;
                                spacing: 5px;
                                alignment: start;
                                toggle-plugin-enable-btn := Button {
                                    text: {
                                        idx == -1 ? "Enable" : SettingsState.plugins[idx].state
                                    };
                                    checkable: true;
                                    enabled: idx != -1 && !SettingsState.plugins[idx].is_busy;
                                    clicked => {
                                        SettingsState.toggle-plugin-enable(
                                            SettingsState.plugins[idx].id);
                                    }
                                }

                                toggle-plugin-auto-start-btn := Button {
                                    text: "Auto start";
                                    checkable: true;
                                    enabled: idx != -1;
                                    clicked => {
                                        SettingsState.toggle-plugin-auto-start(
                                            SettingsState.plugins[idx].id, idx);
                                    }
                                }

                                Button {
                                    text: "Info";
                                    enabled: idx != -1;
                                    clicked => {
                                        debug("Showing info for: " + SettingsState.plugins[idx].id);
                                    }
                                }
                            }
                        }
                    }
                }

                SettingsSection {
                    title: "Keybindings";
                    VerticalLayout {
                        spacing: 8px;
                        for setting[idx] in SettingsState.binding-settings: HorizontalLayout {
                            spacing: 10px;
                            Text {
                                text: setting.label;
                                vertical-alignment: center;
                                width: 120px;
                            }

                            LineEdit {
                                text: setting.value;
                                enabled: false; // TODO: make the update settings work and validate
                                accepted(val) => {
                                    SettingsState.update-setting(setting.id, val, "binding");
                                }
                            }
                        }
                    }
                }

                Rectangle {
                    vertical-stretch: 1;
                }
            }
        }
    }
}
