import { Palette, Button, StandardButton } from "std-widgets.slint";


export global SettingsState {
    in property <int> image-cache-count;
    callback clear-image-cache();
    callback get-image-cache-count();

    // in property <Plugins> plugins; // state, turn off/on, auto-start (bool), show folder, capabilities, version, Optional<extensions>
}

export component ClearImageCacheDiaglog inherits Dialog {
    Text {
        text: "Do you want to clear the image cache?";
    }

    StandardButton {
        kind: yes;
    }

    StandardButton {
        kind: no;
    }
}

export component Settings inherits PopupWindow {
    close-policy: no-auto-close;

    Rectangle {
        background: Palette.background;
        border-radius: 3px;
        drop-shadow-color: black;
        drop-shadow-blur: 50px;
        VerticalLayout {
            Rectangle {
                width: 100%;
                height: 25px;
                background: Palette.background.brighter(30%);
                HorizontalLayout {
                    padding-left: 5px;
                    Text {
                        text: "Settings";
                        font-size: 14px;
                        vertical-alignment: center;
                    }

                    Button {
                        width: parent.height * 2;
                        icon: @image-url("icons/close-button.svg");
                        colorize-icon: true;
                        clicked => {
                            root.close();
                        }
                    }
                }
            }

            Rectangle {
                VerticalLayout {
                    padding: 10px;
                    HorizontalLayout {
                        height: 25px;
                        width: 100%;
                        padding-left: 5px;
                        Text {
                            text: "Image cache count: " + SettingsState.image-cache-count;
                        }

                        Button {
                            text: "Clear";
                            width: 75px;
                            clicked => {
                                SettingsState.clear-image-cache();
                                SettingsState.get-image-cache-count();
                            }
                        }
                    }

                    Rectangle { }
                }
            }
        }
    }
}
